In [51]:
import pandas as pd
import matplotlib.pylab as plt

# create and evaluate a static autoregressive model
from pandas import read_csv
from matplotlib import pyplot
from sklearn.metrics import mean_squared_error
import seaborn as sns

import numpy as np
import folium


import numpy as np
import geoplot as gplt
import geopandas as gpd

In [52]:
read_file = pd.read_csv (r'Full Dataset.txt')
read_file.to_csv (r'Full Dataset.csv', index=None)
data = read_file
data = data.drop(columns=['Unnamed: 0'])
data.head()

,Country.Territory,Code,Year,Meningitis,Alzheimer.s.Disease.and.Other.Dementias,Parkinson.s.Disease,Nutritional.Deficiencies,Malaria,Drowning,Interpersonal.Violence,...,Poisonings,Protein.Energy.Malnutrition,Road.Injuries,Chronic.Respiratory.Diseases,Cirrhosis.and.Other.Chronic.Liver.Diseases,Digestive.Diseases,Fire..Heat..and.Hot.Substances,Acute.Hepatitis,Population,Gross Domestic Product(GDP)
0,Afghanistan,AFG,1990,2159,1116,371,2087,93,1370,1538,...,338,2054,4154,5945,2673,5005,323,2985,10694796,NaN
1,Afghanistan,AFG,1991,2218,1136,374,2153,189,1391,2001,...,351,2119,4472,6050,2728,5120,332,3092,10745167,NaN
2,Afghanistan,AFG,1992,2475,1162,378,2441,239,1514,2299,...,386,2404,5106,6223,2830,5335,360,3325,12057433,NaN
3,Afghanistan,AFG,1993,2812,1187,384,2837,108,1687,2589,...,425,2797,5681,6445,2943,5568,396,3601,14003760,NaN
4,Afghanistan,AFG,1994,3027,1211,391,3081,211,1809,2849,...,451,3038,6001,6664,3027,5739,420,3816,15455555,NaN

In [53]:
#World data
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
world = world.rename(columns={'iso_a3': 'Code'})
#world

/var/folders/ht/wqwf_49s08j701rr8fyvjws00000gn/T/ipykernel_11930/1018360280.py:2: FutureWarning: The geopandas.dataset module is deprecated and will be removed in GeoPandas 1.0. You can get the original 'naturalearth_lowres' data from https://www.naturalearthdata.com/downloads/110m-cultural-vectors/.
  world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

In [54]:
merged_data = pd.merge(world, data, on = 'Code')
merged_data = pd.DataFrame(merged_data)

In [55]:
merged_data

,pop_est,continent,name,Code,gdp_md_est,geometry,Country.Territory,Year,Meningitis,Alzheimer.s.Disease.and.Other.Dementias,...,Poisonings,Protein.Energy.Malnutrition,Road.Injuries,Chronic.Respiratory.Diseases,Cirrhosis.and.Other.Chronic.Liver.Diseases,Digestive.Diseases,Fire..Heat..and.Hot.Substances,Acute.Hepatitis,Population,Gross Domestic Product(GDP)
0,889953.0,Oceania,Fiji,FJI,5496,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000...",Fiji,1990,26,36,...,3,21,95,400,62,126,23,4,780430,2.640836e+09
1,889953.0,Oceania,Fiji,FJI,5496,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000...",Fiji,1991,26,37,...,3,21,94,405,62,126,23,4,784832,2.569533e+09
2,889953.0,Oceania,Fiji,FJI,5496,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000...",Fiji,1992,26,37,...,3,21,93,407,62,126,23,4,786859,2.726275e+09
3,889953.0,Oceania,Fiji,FJI,5496,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000...",Fiji,1993,27,37,...,3,21,94,411,63,126,23,4,789198,2.784346e+09
4,889953.0,Oceania,Fiji,FJI,5496,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000...",Fiji,1994,27,38,...,3,21,94,413,63,127,24,4,790803,2.926347e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5035,11062113.0,Africa,S. Sudan,SSD,11998,"POLYGON ((30.83385 3.50917, 29.95350 4.17370, ...",South Sudan,2015,2390,423,...,188,2992,1011,1295,1614,2607,236,222,11194299,1.199780e+10
5036,11062113.0,Africa,S. Sudan,SSD,11998,"POLYGON ((30.83385 3.50917, 29.95350 4.17370, ...",South Sudan,2016,2240,428,...,179,2723,970,1290,1611,2587,225,207,11066105,NaN
5037,11062113.0,Africa,S. Sudan,SSD,11998,"POLYGON ((30.83385 3.50917, 29.95350 4.17370, ...",South Sudan,2017,2083,436,...,170,2442,955,1293,1634,2612,214,196,10658226,NaN
5038,11062113.0,Africa,S. Sudan,SSD,11998,"POLYGON ((30.83385 3.50917, 29.95350 4.17370, ...",South Sudan,2018,2005,446,...,168,2265,978,1313,1674,2667,211,194,10395329,NaN
5039,11062113.0,Africa,S. Sudan,SSD,11998,"POLYGON ((30.83385 3.50917, 29.95350 4.17370, ...",South Sudan,2019,1968,456,...,166,2139,991,1331,1707,2713,259,191,10447666,NaN

In [35]:
#merged_data.columns.unique()[0]

'pop_est'

In [64]:
full_data_geo = merged_data.drop(['pop_est','name', 'gdp_md_est'], axis = 1)

In [67]:
read_file.to_csv (r'full_data_geo.csv', index=None)

In [66]:
full_data_geo

,continent,Code,geometry,Country.Territory,Year,Meningitis,Alzheimer.s.Disease.and.Other.Dementias,Parkinson.s.Disease,Nutritional.Deficiencies,Malaria,...,Poisonings,Protein.Energy.Malnutrition,Road.Injuries,Chronic.Respiratory.Diseases,Cirrhosis.and.Other.Chronic.Liver.Diseases,Digestive.Diseases,Fire..Heat..and.Hot.Substances,Acute.Hepatitis,Population,Gross Domestic Product(GDP)
0,Oceania,FJI,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000...",Fiji,1990,26,36,22,21,0,...,3,21,95,400,62,126,23,4,780430,2.640836e+09
1,Oceania,FJI,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000...",Fiji,1991,26,37,22,21,0,...,3,21,94,405,62,126,23,4,784832,2.569533e+09
2,Oceania,FJI,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000...",Fiji,1992,26,37,23,21,0,...,3,21,93,407,62,126,23,4,786859,2.726275e+09
3,Oceania,FJI,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000...",Fiji,1993,27,37,24,22,0,...,3,21,94,411,63,126,23,4,789198,2.784346e+09
4,Oceania,FJI,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000...",Fiji,1994,27,38,24,22,0,...,3,21,94,413,63,127,24,4,790803,2.926347e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5035,Africa,SSD,"POLYGON ((30.83385 3.50917, 29.95350 4.17370, ...",South Sudan,2015,2390,423,90,3039,5171,...,188,2992,1011,1295,1614,2607,236,222,11194299,1.199780e+10
5036,Africa,SSD,"POLYGON ((30.83385 3.50917, 29.95350 4.17370, ...",South Sudan,2016,2240,428,91,2767,5032,...,179,2723,970,1290,1611,2587,225,207,11066105,NaN
5037,Africa,SSD,"POLYGON ((30.83385 3.50917, 29.95350 4.17370, ...",South Sudan,2017,2083,436,92,2485,4983,...,170,2442,955,1293,1634,2612,214,196,10658226,NaN
5038,Africa,SSD,"POLYGON ((30.83385 3.50917, 29.95350 4.17370, ...",South Sudan,2018,2005,446,95,2306,4885,...,168,2265,978,1313,1674,2667,211,194,10395329,NaN
5039,Africa,SSD,"POLYGON ((30.83385 3.50917, 29.95350 4.17370, ...",South Sudan,2019,1968,456,97,2180,5109,...,166,2139,991,1331,1707,2713,259,191,10447666,NaN

In [2]:
import os
os.getcwd()

'/Users/christinesojberg/Data viz project'